### ISSUE TITLE
Not working in Lumen 5.8 with latest spatie/laravel-permission v3.17.0

### ISSUE THREAD

**Issue by bojidartonchev** [irazasyed/larasupport#23]
Hello,

I had the following issue after upgrading both **spatie/laravel-permission** and **larasupport** to latest versions.

```
[2020-10-13 08:44:11] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Lumen\Application::configPath() in /var/www-hosts/FondleApi/vendor/irazasyed/larasupport/src/helpers.php:44
Stack trace:
#0 /var/www-hosts/FondleApi/vendor/spatie/laravel-permission/src/PermissionServiceProvider.php(19): config_path()
#1 [internal function]: Spatie\Permission\PermissionServiceProvider->boot()
#2 /var/www-hosts/FondleApi/vendor/illuminate/container/BoundMethod.php(32): call_user_func_array()
#3 /var/www-hosts/FondleApi/vendor/illuminate/container/BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www-hosts/FondleApi/vendor/illuminate/container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#5 /var/www-hosts/FondleApi/vendor/illuminate/container/Container.php(576): Illuminate\Container\BoundMethod::call()
#6 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Application.php(244): Illuminate\Container\Container->call()
#7 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Application.php(229): Laravel\Lumen\Application->bootProvider()
#8 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#9 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Application.php(230): array_walk()
#10 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Console/Kernel.php(113): Laravel\Lumen\Application->boot()
#11 /var/www-hosts/FondleApi/artisan(35): Laravel\Lumen\Console\Kernel->handle()
#12 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Lumen\\Application::configPath() at /var/www-hosts/FondleApi/vendor/irazasyed/larasupport/src/helpers.php:44)
```

After downgrading **larasupport** to v1.6.0, it is working fine.

Could you please assist me in resolving this?

Best regards.

**Comment by irazasyed** [comment]
Hi, You need to upgrade your version of Lumen to at least `>=6` as the `configPath()` method is available from `6.x` version of Lumen framework. Consider using latest version!
